### ISSUE TITLE
go get returning an error

### ISSUE THREAD

**Issue by CallumVass** [pilu/fresh#13]
Hi,

When I try a `go get github.com/pilu/fresh` I get the following error:

![image](https://cloud.githubusercontent.com/assets/2204920/3159620/c516b8f0-eb13-11e3-9eee-62ec9cd20884.png)

Any idea how I fix this? Thanks.

**Comment by gmccue** [comment]
@kpashka is this still an issue for you?

**Comment by kpashka** [comment]
@gmccue It's not, because I'm not using Windows anymore 😆
