### ISSUE TITLE
Cross-Compile

### ISSUE THREAD

**Issue by pjebs** [pilu/fresh#31]
Is there any flags to specify the exact build parameters:

I run a mac but I want to build a linux executable.
I use this command:

GOOS=linux GOARCH=amd64 go build -o main.linux main.go

**Comment by pjebs** [comment]
In fact, I don't even want fresh to run it (since it can't on a mac platform).
I just want it to compile the code as I make changes.

(I actually run it on my linux vagrant virtual machine)

**Comment by pjebs** [comment]
In fact, I don't even want fresh to run it (since it can't on a mac platform).
I just want it to compile the code as I make changes.

(I actually run it on my linux vagrant virtual machine)

**Comment by pilu** [comment]
@pjebs unfortunately it's not possible in this version. it will be in the new version I'm working on

**Comment by pjebs** [comment]
When is the new version expected?
