### ISSUE TITLE
Double restart?

### ISSUE THREAD

**Issue by Mitranim** [pilu/fresh#32]
Using `fresh` with a small Go server on OS X. Whenever I save a file, `fresh` recompiles and restarts the application twice. Is this common? How to troubleshoot this?

Other than this small issue, really enjoying the tool. Please keep it up!

**Comment by pilu** [comment]
@Mitranim it's not commond, but you can run it with the verbose option to see what's happening. is it possible that your editor saves twice and fresh compiles twice? you can try increasing the `build_delay` option

**Comment by Mitranim** [comment]
I'm sorry but I don't see a verbose option in the configuration. Anyway what I'm seeing in the terminal is that `watcher` sends the `MODIFY|ATTRIB` event (for the same file) twice. This happens even when using the `touch` utility to modify the file, so this doesn't appear to be editor related.

**Comment by Mitranim** [comment]
Some additional notes. The folder is in a git repo; it's not inside Dropbox or anything like that, and I don't believe I have any daemons watching this location; quitting the editor and restarting Finder has no effect. Would love to hear other troubleshooting suggestions. :)

**Comment by pilu** [comment]
I remember in the past it was an issue with fsnotify, that's why I introduced the delay option, to avoid this problem and just building once if I receive a second event just after the first one. it might be solved with go-fsnotify

**Comment by Mitranim** [comment]
Increasing the delay to `2000` does solve the issue, but that's a lot of waiting. I'm not entirely sure what you mean by solving this with `go-fsnotify`. Any clue please?

**Comment by pilu** [comment]
yes, 2000 is too much, when I had that problem my editor was saving twice, but the second event was something like 100 ms after the first one. 
about fsnotify, I'm using github.com/howeyc/fsnotify to watch the fs, but I think https://github.com/go-fsnotify/fsnotify is more up to date, switching to that may solve the issue, I'm not sure.

**Comment by Mitranim** [comment]
Trying out your suggestion. Installed https://gopkg.in/fsnotify.v0 per the recommendation on https://github.com/go-fsnotify/fsnotify#api-stability, switched `fresh` to it, recompiled binary. No observable change so far. The watcher still fires two events per file modification. =( And the newer version of `go-fsnotify` has a different API. =/

**Comment by gmccue** [comment]
@Mitranim is this still an issue?

**Comment by Mitranim** [comment]
@gmccue Haven't checked since last year, and I don't remember how it ended up, sorry.
