### ISSUE TITLE
abandoned?

### ISSUE THREAD

**Issue by pkieltyka** [pilu/fresh#36]
Hey @pilu - just wondering if you're no longer supporting fresh? .. it's a great project and my team uses it everyday (my fork though, since its quite stale) .. whats up?

**Comment by pilu** [comment]
hi @pkieltyka, thank you! I'm actually building a new fresh2 from scratch to have multiple groups of custom commands, I hope to finish it soon and merge or use all the open PR

**Comment by pkieltyka** [comment]
thats awesome :) looking forward to trying it

**Comment by baijum** [comment]
I waited for pull reuest #16 to be committed for one year.  Like many others I also use a personal fork of this project: https://github.com/baijum/refresh

**Comment by pilu** [comment]
Hi @baijum , I never merged that PR, it's importing the wrong pkg ("github.com/ae0000/fresh/runner"), there is a comment too.

**Comment by baijum** [comment]
@pilu I added that comment :) There are two other pull requests which does the same thing: #20 #26
These three pull requests takes slightly different approaches.

**Comment by pilu** [comment]
nice thank you @baijum , I hope to finish the new version soon and merge everything in the new branch

**Comment by pkieltyka** [comment]
@pilu btw, while you're working on fresh2, keep in mind the GO15VENDOREXPERIMENT where projects will have a `./vendor` folder in their projects. I personally don't think that folder should be listened to.. it would be far too many events to listen to, and similar to how fresh doesnt listen to $GOPATH packages. One easy way to solve this is to offer ability to exclude directories from fresh listening.

**Comment by jchannon** [comment]
How goes fresh2?

**Comment by pilu** [comment]
@jchannon it going slowly, I don't have much time lately for this. I think I'll finish the base part and start accepting PR if anyone is interested

**Comment by pilu** [comment]
@pkieltyka @jchannon @baijum  guys I think I won't be able to finish the new version soon, so I'll be happy to receive PR or give you access to the repo if you are interested

**Comment by VojtechVitek** [comment]
Check out this fork: https://github.com/pressly/fresh. It has a lot of cherry-picked fixes and some other improvements.

**Comment by gmccue** [comment]
@pilu I would be happy to help maintain this project if you like. I would prefer doing so rather than keeping this repo "abandoned".

**Comment by pilu** [comment]
thank you @gmccue. that would be awesome. do you think it's better if you commit here or do you prefer to fork it? then I link link to your forks guys. let me know please.

**Comment by gmccue** [comment]
@pilu why not keep it here? You already have 700+ stars.

**Comment by pilu** [comment]
ok guys I can give you access here if you want

**Comment by gmccue** [comment]
@pilu sounds good!

**Comment by gmccue** [comment]
@pilu any news here? I would gladly review the open PRs and tickets.

**Comment by pilu** [comment]
@gmccue I added you :metal:

**Comment by pkieltyka** [comment]
btw, we have an improved version at https://github.com/pressly/fresh that we're maintaining

**Comment by pilu** [comment]
added @pkieltyka as well!

**Comment by gmccue** [comment]
@pkieltyka @VojtechVitek maybe you could submit a PR with your updated fork to this repo?

**Comment by VojtechVitek** [comment]
@gmccue afaik, our fork doesn't have backward compat. config file. //cc @c2h5oh?

**Comment by pkieltyka** [comment]
hey guys, we talked it over and decided we're just going to keep our fork .. we don't have the time to maintain the project, pressly/fresh has just a few fixes for us.. feel free to pick from it if you need. but for the most part we're going to keep our fork as is

**Comment by jaybeecave** [comment]
Hi, can someone update the readme to contain a link to the best fork?

Spent 10 mins tracking down the best fork for this, it is a very good solution and the best version of it should be readily available/obvious.

**Comment by gmccue** [comment]
@pilu would you mind creating a project to build on Travis CI (or giving me permissions to do so)?

**Comment by gmccue** [comment]
I am now helping to actively maintain this repo. More bug fixes are on the way.

**Comment by pilu** [comment]
thank you @gmccue for your work! 🤘

**Comment by gmccue** [comment]
@pilu if you could setup a Travis CI build for the project that would still be great :)

**Comment by pilu** [comment]
@gmccue just activated! https://travis-ci.org/pilu/fresh

**Comment by gmccue** [comment]
@pilu Perfect! Thanks a million.
