### ISSUE TITLE
question

### ISSUE THREAD

**Issue by gedw99** [pilu/fresh#38]
fresh is neat thanks. Really liking golang

Its a tool, and so is not imported into my project code.
i use glide for vendoring. works well with golang 1.5 so far.

Now, my question is:
How can i ensure that fresh is installed as a tool for each project ?
One way is to make it a "cmd" in my project maybe... Not sure.

**Comment by pilu** [comment]
I think it's better to have it as a tool in your system and not as a
dependency for your project.
There are workaround to do that but I would suggest to just install it in
your system separately.

On 26 August 2015 at 13:21, Ged <notifications@github.com> wrote:

> fresh is neat thanks. Really liking golang
>
> Its a tool, and so is not imported into my project code.
> i use glide for vendoring. works well with golang 1.5 so far.
>
> Now, my question is:
> How can i ensure that fresh is installed as a tool for each project ?
> One way is to make it a "cmd" in my project maybe... Not sure.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pilu/fresh/issues/38>.
>



-- 
Andrea Franz
http://gravityblast.com
http://twitter.com/gravityblast
