### ISSUE TITLE
too many open files issue

### ISSUE THREAD

**Issue by dev-ahmed** [pilu/fresh#44]
i always face this issue when i run this command 

"inotify_init: too many open files"

 any suggestions ?

**Comment by c2h5oh** [comment]
Your OS is limiting the number of files you can watch at the same time. How you increase that limit depends on your OS.

**Comment by pilu** [comment]
@dev-ahmed how many files do you have? this commit fied it up to 10000 https://github.com/pilu/fresh/commit/f6e0ef3d7a7f4094b2abfd03f0e30f616bd15368

**Comment by dev-ahmed** [comment]
@c2h5oh am using Ubuntu 15.10 , what are the procedures to increase this limit ?

**Comment by aaudis** [comment]
I run in similar issue 

What I did

I increased `fs.inotify.max_user_instances = 1024` in `/etc/sysctl.conf`, my value was 128

If option `fs.inotify.max_user_instances` is not defined in `/etc/sysctl.conf` you simply add it

after you change your `/etc/sysctl.conf`

run commands:

```
$ sudo sysctl -p
$ sudo sysctl -a
```

this should fix your problem

**Comment by bodyno** [comment]
use runner.conf to ignore some fold

**Comment by Gujarats** [comment]
@pilu @aaudis The solution for increasing the `fs.inotify.max_user_instances` = 1024 in `/etc/sysctl.conf`.
Only works for temporary, this will happen again after several changes I have made with the file.

In my cases I change the `_examples/traffic/main.go` for several times and the error `| 10:23:35 app         | inotify_init: too many open files` shows again.

it seems that we need to limit the file watcher, but I'm not sure.

**Comment by DarkDrim** [comment]
I have the same problem, I use docker

**Comment by senseluo** [comment]
for me just creating a ` fresh.conf ` in root folder:

```
root:              ./
tmp_path:          ./tmp
build_name:        api
valid_ext:         .go, .tpl, .tmpl, .html
no_rebuild_ext:    .tpl, .tmpl, .html
ignored:           ./vendor, tmp
build_delay:       600
colors:            1
```
