### ISSUE TITLE
Adjust logging verbosity?

### ISSUE THREAD

**Issue by robbles** [pilu/fresh#49]
Is there a setting for this? It looks like there isn't anything referenced in the config file.

The reason I'm asking is that I have a `vendor` directory, and `fresh` logs everything in there on startup, like so: 

```
12:52:11 watcher     | Watching .
12:52:11 watcher     | Watching vendor
12:52:11 watcher     | Watching vendor/github.com
12:52:11 watcher     | Watching vendor/github.com/julienschmidt
12:52:11 watcher     | Watching vendor/github.com/julienschmidt/httprouter
12:52:11 watcher     | Watching vendor/github.com/kelseyhightower
12:52:11 watcher     | Watching vendor/github.com/kelseyhightower/envconfig
...
```

There's also a bunch of what looks like debug output about receiving events, checking for file existence, etc.

It looks like you've got these logs nicely separated into different loggers already from the output, so I guess what I'm really asking for is a way to only see the output from the `build` and `runner` loggers.

**Comment by pilu** [comment]
Hi @robbles , there's no option for that but you are right, it something to have, I'll try to do it for the next version.
