### ISSUE TITLE
Dockerized !

### ISSUE THREAD

**Issue by metal3d** [pilu/fresh#53]
Hi,
It's not an issue, just to say that I'm using a docker container I've made and finally gave it to the community:
https://hub.docker.com/r/metal3d/go-fresh/

You may try, it works like a charm at home. It's nice to work with other containers as linked mongo database by docker-compose. I'm using "Glide" to get "vendor" directory in my project, no need to install them in the container now.

**Comment by gmccue** [comment]
@metal3d Thanks! If you would like to add this to the `README` you can create a PR to do so.

**Comment by metal3d** [comment]
I should update my docker image before. But right, I'll do it :)

BTW: big thanls for your work
