### ISSUE TITLE
Performance suggestion

### ISSUE THREAD

**Issue by cristian-sima** [pilu/fresh#56]
I wait a long time for the first time to load it. I got a lot of messages which I do not care about

![image](https://cloud.githubusercontent.com/assets/12199042/16880291/40b9409e-4abd-11e6-88ea-ace778a8ecc8.png)

From my own expirence I know that a log takes a lot of time. So, it may be a good suggestion to not display the ignored directories, but just the ones that I am interested in wathcing

What do you think?

**Comment by gmccue** [comment]
Fixed by #60
