### ISSUE TITLE
fresh: command not found on Ubuntu

### ISSUE THREAD

**Issue by k0fi** [pilu/fresh#74]
I installed fresh using go get and I see it being placed at `~/go/src/github.com/pilu/fresh`.
 
>  echo $GOPATH
> /home/me/go

I can build and run my project at `~/go/src/myapp`, but as for fresh I get:

```
me@pc:~/go/src/myapp$ fresh
fresh: command not found
```

How can I fix this?

**Comment by codeblooded** [comment]
what is your `$PATH`? Do you see `fresh` in `~/go/bin`?

**Comment by k0fi** [comment]
Here is the $PATH:

```
me@pc:~/go/bin$ echo $PATH
/home/me/google-cloud-sdk/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/sbin:/bin
```
And yes, I see `fresh` in `~/go/bin`

**Comment by JamesRichard-son** [comment]
k0fi looks like you have not set the path try setting it in ~./bashrc 

`export GOPATH=$HOME/go`
`export PATH=$PATH:$GOROOT/bin:$GOPATH/bin`

add the 2 lines and you should be good.

**Comment by AndreaM16** [comment]
@JamesRichard-son solution worked for me. Just adding the PATH as `export PATH=$PATH:$GOROOT/bin:$GOPATH/bin`.

`> go env`

    GOARCH="amd64"
    GOBIN=""
    GOEXE=""
    GOHOSTARCH="amd64"
    GOHOSTOS="linux"
    GOOS="linux"
    GOPATH="/home/andream16/go"
    GORACE=""
    GOROOT="/usr/lib/go"
    GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
    GCCGO="gccgo"
    CC="gcc"
    GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build868950532=/tmp/go-build -gno-record-gcc-switches"
    CXX="g++"
    CGO_ENABLED="1"
    PKG_CONFIG="pkg-config"
    CGO_CFLAGS="-g -O2"
    CGO_CPPFLAGS=""
    CGO_CXXFLAGS="-g -O2"
    CGO_FFLAGS="-g -O2"
    CGO_LDFLAGS="-g -O2"

**Comment by Gujarats** [comment]
You can fix this using this step : 
1. go to the source fresh and build it : `cd $GOPATH/github.com/pilu/fresh` and `go build` in root of the project.
2. now the `fresh` file will exist if no error happen, you can place this in your `/usr/bin/local/`  so that `fresh` command will exist.

**Comment by KingPuiWong** [comment]
- **go env** find your GOPATH 
- cd GOPATH/bin,run go install github.com/pilu/fresh 
- cd /path/yourcode ,run fresh
- done
