### ISSUE TITLE
inotify_init: too many open files

### ISSUE THREAD

**Issue by yoesoff** [pilu/fresh#79]
Hi, I got issue after adding so many js dependencies in my project folder thru npm.
my question is how to ignore some specific folder(s) to avoid this kind of error ?

`inotify_init: too many open files`

![image](https://user-images.githubusercontent.com/241982/29750205-ee666bf6-8b65-11e7-81ce-994ad522a737.png)

Thanks in advance,

**Comment by yoesoff** [comment]
sorry for this

**Comment by zwhitchcox** [comment]
What was your solution?
