### ISSUE TITLE
Config :log_color_app is not working

### ISSUE THREAD

**Issue by slier81** [pilu/fresh#81]
As title, i set `log_color_app = blue`, yet my application log text is still in white

**Comment by tiger-regit** [comment]
Here' s my screenshots

![image](https://user-images.githubusercontent.com/6560524/40471098-3f0ddb8a-5f68-11e8-8921-e07e51d99c10.png)

It's working

**Comment by slier81** [comment]
@tiger-regit strange..mine not working..btw i already abandon this project since its not being maintained anymore..Currently im using `realize`
